services:
  - type: web
    name: travelling-agency-management
    env: docker
    plan: free

    dockerfilePath: ./Dockerfile

startCommand: >
    php artisan config:clear &&
    php artisan cache:clear &&
    php artisan migrate --force