services:
  - type: web
    name: travelling-agency-management
    env: docker
    plan: free

    dockerfilePath: ./Dockerfile

    startCommand: >
      php artisan config:clear &&
      php artisan cache:clear &&
      php artisan key:generate &&
      php artisan migrate --force &&
      php artisan serve --host 0.0.0.0 --port 10000